config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'dashboard#login'


  resources :users do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :due_date, presence: true
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController

  def login; end

  def index
    @status = %w[open in_progress done]
  end

end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @user = User.find(params[:user_id])
    @task = @user.tasks.create(task_params)

    if @task.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  def edit
    @task = Task.find(params[:id])
    @status = %w[open in_progress done]
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_edit_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :due_date, :status)
  end

  def task_edit_params
    params.require(:task).permit(:status)
  end

end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1>Hello <%= current_user.email %> </h1>

<h2>My Tasks</h2>

<ul>
  <% current_user.tasks.each do |task| %>
    <li class="task">
      <div class="float-left">
      <b><%= task.title %></b><br>
      <%= task.description %><br>
      Due date: <%= task.due_date.strftime("%m/%d/%Y") %>
        <%= form_with(url: user_task_path(current_user.id, task.id), model:task ,method: :patch, local: true) do |f| %>
          <%= f.select :status, @status.map { |t| [t]}, {prompt: if task.status?; task.status else "please select" end, class: 'some-css-class' }, onchange: 'this.form.requestSubmit()' %>
        <% end %>
      </div>
      <div class="float-right">
      <%= link_to "edit", edit_user_task_path(current_user.id, task.id), :class => "btn-primary mx-auto" %>
      <%= link_to "delete", user_task_path(current_user.id, task.id), :class => "btn-secondary mx-auto text-white bg-red-700", data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
      </div>
      <br class="clear-both">
    </li>
  <% end %>
</ul>
<%= link_to "add new task", new_user_task_path(current_user.id), :class => "btn-primary mx-auto" %>
<% if user_signed_in? %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, :class => "btn-primary block mx-auto" %>
<% end %>

app/views/dashboard/login.html.erb
<h1 class="text-3xl text-center text-black font-bold mt-80 mb-20">TASK MANAGER</h1>

<% if user_signed_in? %>
  <div> Welcome <%= current_user.email %> </div>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, :class => "btn-primary block mx-auto" %>
<% else %>
  <%= button_to "Sign in" , new_user_session_path, :class => "btn-primary block mx-auto" %>
<% end %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskmanager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose">
  <div class="container mx-auto mt-10">

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [ current_user, current_user.tasks.build ] do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% current_user.errors.full_messages_for(:title).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% current_user.errors.full_messages_for(:description).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :due_date %><br>
    <%= form.date_select :due_date %>
    <% current_user.errors.full_messages_for(:due_date).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit :class => "btn-primary" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= form_with(model: [current_user, @task]) do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% current_user.errors.full_messages_for(:title).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% current_user.errors.full_messages_for(:description).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :due_date %><br>
    <%= form.date_select :due_date %>
    <% current_user.errors.full_messages_for(:due_date).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, @status.map { |t| [t]}, {}, class: "form-control" %>
    <% current_user.errors.full_messages_for(:status).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit :class => "btn-primary" %>
  </div>
<% end %>

<%= link_to "back to dashboard", root_path, :class => "btn-secondary" %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>


<ul>
  <% current_user.tasks.each do |task| %>
    <li class="task">
      <%= task.title %><br>
      <%= task.description %><br>
      <%= task.due_date %>
      <%= link_to "edit", edit_user_task_path(current_user.id, task.id), :class => "btn-primary mx-auto" %>
    </li>
  <% end %>
</ul>

<%= link_to "add new task", new_user_task_path(current_user.id), :class => "btn-primary mx-auto" %>
<% if user_signed_in? %>
  <%= button_to "Sign out", destroy_user_session_path, method: :delete, :class => "btn-primary block mx-auto" %>
<% end %>

app/views/tasks/new.html.erb
<h1 class="headline-h2">New Task</h1>


<%= render "form" %>

<%= link_to "back to dashboard", root_path, :class => "btn-secondary" %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.description %></p>

app/views/users/index.html.erb
<h1>Users</h1>


<ul>
  <% @users.each do |user| %>
    <li>
      <%= user.email %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>


<%= form_with model: [ @user, @user.tasks.build ] do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% @user.errors.full_messages_for(:title).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
    <% @user.errors.full_messages_for(:description).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :due_date %><br>
    <%= form.date_select :due_date %>
    <% @user.errors.full_messages_for(:due_date).each do |message| %>
      <div class="text-red-600"><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit :class => "btn-primary" %>
  </div>
<% end %>